### ISSUE TITLE
Need update support for Create0.5.1a

### ISSUE THREAD

**Issue by mlus-asuka** [Janoeo/JER-Integration#11]
the new version is no longer supported.

NoClassDefFoundError:com/simibubi/create/foundation/config/AllConfigs in (CreateWorldGen.java:26) (CreateWorldGen.java:36)

**Comment by AlasDiablo** [comment]
Bug fix with #12 thank to @SiverDX

**Comment by AlasDiablo** [comment]
Oops, i reopen the issues until i do a release
