### ISSUE TITLE
1.18.2 Startup crash/Incompatibility issue?

### ISSUE THREAD

**Issue by xFirefalconx** [Janoeo/JER-Integration#15]
Hi, I added this mod to my modpack yesterday. 
#14 mentioned Create (same update I am using) before so this *might* be a duplicate, however there could be other incompatibilities? 
[crash-2023-06-01_20.09.31-fml.txt](https://github.com/Janoeo/JER-Integration/files/11629605/crash-2023-06-01_20.09.31-fml.txt)
[2023-06-01-1.log](https://github.com/Janoeo/JER-Integration/files/11629627/2023-06-01-1.log)

Please see to let me know if/once the above mentioned issue is resolved - I will recheck my situation then and give feedback. 
If the error logs however show any particular different error, let me know, I'll try to help gather information then. 

Request mod list if necessary, please. Currently 300 mods running.

**Comment by Mikaaah** [comment]
Experiencing the Same issue! 
[crash-2023-06-04_22.40.04-fml.txt](https://github.com/Janoeo/JER-Integration/files/11646616/crash-2023-06-04_22.40.04-fml.txt)

**Comment by SiverDX** [comment]
The current latest version of 1.18.2 does not support the new Create version 0.5.1*
