### ISSUE TITLE
not working on/with servers

### ISSUE THREAD

**Issue by VastayanWings** [Janoeo/JER-Integration#6]
as the title says i installed the mod on client and on a forge server, both are forge version 40.1.19 (minecraft 1.18.2) and the mod didnt worked at all. going into a singleplayer world did show the mob-drops of alex's mobs and create ores-spawns, but were missing the cobalt ore spawns from tinkers construct. 
going on server (once again: server has mod installed too) did show neither of any of the above

checked the servers logs and debug-logs and both said the mod initialised/loaded without any issue

can provide more info like modlist or logfiles when requested

used mod-version was 3.2.1

**Comment by Gbergz** [comment]
Can confirm this!

**Comment by AlasDiablo** [comment]
The version 3.3.0 (in review on curseforge) is fixing this issues, i hope (is working on my dev env). ^^'
