### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by smolinacadena** [Janoeo/JER-Integration#7]
Hello,

I'm emperiencing a crash on startup in a modpack with several other mods. I'm attaching the logs and the crash report.

Logs: https://pastebin.com/86kR70af
Crash report: https://pastebin.com/R3D4FN5s

All version information: Forge, Java, etc can be found in the crash report.

Here's the modpack I'm testing: https://www.curseforge.com/minecraft/modpacks/primatilandia

If you add the mod, you'll get the error.

Thankful for any assistance you can provide.

**Comment by drakray** [comment]
Very probably caused by create 0.5.0.d, all subMods crashed (API changes)

**Comment by AlasDiablo** [comment]
> Very probably caused by create 0.5.0.d, all subMods crashed (API changes)

Yes, is mostly cause by this, the field name of each ore have change to some thing else (error: `java.lang.NoSuchFieldError: ZINC_ORE`)
I will look into updating JER Intregration tomorrow.

**Comment by AlasDiablo** [comment]
To avoid any similar problem i will add a options via config to manually disable a specific implementation.

**Comment by smolinacadena** [comment]
Just put a PR for this, not sure if it's what it's needed. But it works.

**Comment by AlasDiablo** [comment]
By just updating the dep it working and i don't understand why... xD
I build a version and i upload it on curseforge right now.

**Comment by radaelilucca** [comment]
I's working now with Create 0.5.0d!
