### ISSUE TITLE
loading bug

### ISSUE THREAD

**Issue by Rasszusz221** [Janoeo/JER-Integration#9]
[crash-2022-08-20_17.32.06-fml.txt](https://github.com/Janoeo/JER-Integration/files/9387584/crash-2022-08-20_17.32.06-fml.txt)
Load fail the zinc ore

**Comment by AlasDiablo** [comment]
Ok, apparently the fix only works in the dev environment.
As temporary fix try disabling `create` in the JER-Integration config file
I re-open the first issue related to this #7
